# Generated by Django 3.2.8 on 2021-10-20 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('allowed_users', models.CharField(max_length=255)),
            ],
        ),
    ]
